Added Enable upload to plugins
mattermost/mattermost-plugin-starter-template pull request #162
Opened 2022-01-25 20:50 UTC by coltoneshaw

#### Summary
```bash
./build/bin/pluginctl deploy com.coltonshaw.additional-banner dist/com.coltonshaw.additional-banner-1.5.1.tar.gz
2022/01/25 15:43:36 Connecting using local mode over /var/tmp/mattermost_local.socket
2022/01/25 15:43:36 Uploading plugin via API.
Failed: failed to upload plugin bundle: : Plugins and/or plugin uploads have been disabled., 
```

Plugin uploads are not enabled by default

2022-01-26 08:45 UTC, hanzei approved these changes
Thanks for the docs update :+1:

2022-01-26 08:45 UTC, hanzei commented on README.md
> +        "EnableUploads" : true
`EnableUploads` need to be enabled regardless of the use of Local Mode. Could the paragraph in `Development` make it clear, that `EnableUploads` needs to be enabled?

2022-01-26 08:45 UTC, hanzei requested changes
Woops, wanted to block on https://github.com/mattermost/mattermost-plugin-starter-template/pull/162/files#r792414228

2022-01-26 14:48 UTC, coltoneshaw commented
@hanzei - I moved it up to be within the dev setup.

2022-01-27 10:33 UTC, hanzei approved these changes
Awesome, thank you Colton!

2022-01-27 10:34 UTC, merged