fix: replace any backticks (`) in manifestStr
mattermost/mattermost-plugin-starter-template pull request #196
Opened 2024-02-11 20:38 UTC by NeilHanlon

#### Summary
if manifestStr (read from plugin.json) has any '`' characters in it, such as when using markdown formatting in a text value, the generated go code fails to build due to unescaped '`' characters, leading the compiler to believe some input is mismatched.

This change passes the manifestStr through a Replacement filter to replace the ` characters with input which will be properly formatted through the compiler.

#### Ticket Link
n/a

2024-02-11 20:38 UTC, mattermost-build commented
Hello @NeilHanlon,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-02-11 20:39 UTC, NeilHanlon commented
/check-cla

2024-02-12 10:31 UTC, hanzei requested changes
Thanks for the contribution @NeilHanlon :+1: 

While the fix seems reasonable, I would like to see a test that verifies that the newly generated manifest is valid.

2024-02-12 13:47 UTC, NeilHanlon commented
> Thanks for the contribution @NeilHanlon 👍
> 
> While the fix seems reasonable, I would like to see a test that verifies that the newly generated manifest is valid.

Absolutely! I will add some tests later--I also found an issue with the typescript generator, as well.. Will have to think about that a bit, unless you have any immediate thoughts on how to support markdown in plugin.json (e.g. https://github.com/rocky-linux/mattermost-plugin-community-toolkit/blob/master/plugin.json)

2024-02-23 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-03-11 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2026-04-21 08:42 UTC, closed without merging